name: Send Pull Requests

on:
  push:
    branches:
      - develop

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Get Branches
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const branches = response.data.map(branch => branch.name);
            core.setOutput('branches', branches.join(','));

      - name: Create Pull Requests
        run: |
          branches=$(echo "${{ steps.GetBranches.outputs.branches }}" | tr ',' '\n')
          for branch in $branches; do
            gh pr create --base main --head $branch --title "Atualização da branch $branch" --body "Essa é uma atualização automática da branch $branch."
          done
