name: Enviar Pull Request

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - name: Obter nome da branch do PR
        run: |
          pr_branch=${GITHUB_HEAD_REF}
          echo "Branch do PR: $pr_branch"
          
      - name: Obter nome da branch
        run: |
          # Extrair apenas o nome da branch da variável GITHUB_REF
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch corrente: $branch_name"
          
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.14.2 # optional, see action.yml for current default
    
      - name: Get Branches
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const branches = response.data.map(branch => branch.name);
            core.setOutput('branches', branches.join(','));
            
      - name: Create Pull Requests
        run: |
          branches=$(echo "${{ steps.GetBranches.outputs.branches }}" | tr ',' '\n')
          for branch in $branches; do
            gh pr create --base main --head $branch --title "Atualização da branch $branch" --body "Essa é uma atualização automática da branch $branch."
          done
